apiVersion: 1

contactPoints:
  - orgId: 1
    name: critical-email-telegram
    receivers:
      - uid: critical-email
        type: email
        settings:
          addresses: ${MS365_ALERT_EMAIL_TO}
          singleEmail: true
        disableResolveMessage: false

  - orgId: 1
    name: warning-email
    receivers:
      - uid: warning-email
        type: email
        settings:
          addresses: ${MS365_ALERT_EMAIL_TO}
          singleEmail: true
        disableResolveMessage: false
