apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: ${VM_DATASOURCE_URL}
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
